# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paul Dufossé personal webpage
email: paul.dufosse@inria.fr
description: > # this means to ignore newlines until "baseurl:"
  My personal webpage. Mostly related to my PhD work in Randomized Optimization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paulduf.github.io" # the base hostname & protocol for your site

remote_theme: "mmistakes/jekyll-theme-basically-basic"

#twitter_username: jekyllrb
github_username:  paulduf
linkedin_username: paulduf

# Build settings
markdown: kramdown
